apiVersion: v1
kind: Pod
metadata:
  name: skopeo 
  namespace: default
spec:
  containers:
  - name: skopeo 
    image: quay.io/skopeo/stable:latest 
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
